#!/bin/bash -e
# Approximate file growth over some seconds
# w/ human friendly display
# Patience points optional
S1=$(stat -c %s $1)
D1=$(date +%s.%N)
for i in {1..3};
do
#	echo -n .
	sleep 1
done
D2=$(date +%s.%N)
S2=$(stat -c %s $1)
#echo
DSDT=$(bc <<< "scale=2; (${S2:-0} - $S1) / 1024 / 1024 / ($D2 - $D1)")
echo $1: $DSDT megabytes/second
